server:
  port: 8088
# 数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zjxdb?useUnicode=true&charaterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT
    username: root
    password: root
    # 连接池中允许的最大连接数。缺省值：10
    maximum-pool-size: 5
    # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
    max-lifetime: 1800000
    # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
    idle-timeout: 600000
    # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
    connection-timeout: 30000
    # 无需指定，除非系统无法自动识别
    driver-class-name: com.mysql.jdbc.Driver
# 日志级别
logging:
  level: info
pagehelper:
    helperDialect: mysql
    # 分页合理化
    reasonable: true
    # 是否支持接口参数来传递分页参数，默认false
    supportMethodsArguments: true
    params: count=countSql